[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase the timeout for functions to handle longer build times
  node_bundler = "esbuild"
  external_node_modules = ["next"]
